First working version Sprint 14
KoRVeRT/java-shareit pull request #2
Opened 2023-05-18 21:12 UTC by KoRVeRT

Создал базу данных
Реализовал функции бронирования
Добавил даты бронирования при просмотре вещей
Добавил возможность оставить отзывы

2023-05-19 19:44 UTC, kalitva requested changes

2023-05-19 19:44 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    public boolean equals(Object o) {
Если хочешь сравнивать только по айди, можешь воспользоваться `@EqualsAndHashCode.Include`

https://www.baeldung.com/java-lombok-equalsandhashcode#including-specific-fields

2023-05-19 19:44 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +        return getClass().hashCode();
О нет, так лучше не делай) Повтори три кровавых правила про контракт между equasl и hashCode

2023-05-19 19:44 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +}
Вместо определения все этих методов можно воспользоваться `Specification` для фильтрации объектов из бд. Если есть время, попробуй переделать, это почти везде используется где есть spring data

https://spring.io/blog/2011/04/26/advanced-spring-data-jpa-specifications-and-querydsl (можно без querydsl)

2023-05-19 19:44 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (booking.getBooker().getId().equals(user.getId())
Лучше инвертировать условие, помнишь про guard clause?

https://www.codementor.io/@clintwinter/use-guard-clauses-for-cleaner-code-1rrsczgwxp

2023-05-19 19:44 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    List<Item> findAllByOwnerIdOrderByIdAsc(Long ownerId);
`findAllByOwnerIdOrderByIdAsc --> findByOwnerIdOrderById`
`All` точно можно убрать, `Asc` скорее всего тоже

2023-05-19 19:44 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            Optional<Booking> lastBooking = bookingRepository
Дело вуса, но я бы обошелся без выделения в переменную (сtrl + alt + n чтобы заинлайнить)

2023-05-20 14:06 UTC, KoRVeRT commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    public boolean equals(Object o) {
Добавил сравнение по другим параметрам.

2023-05-20 14:19 UTC, KoRVeRT commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (booking.getBooker().getId().equals(user.getId())
Помню и постоянно забываю)

2023-05-21 19:56 UTC, kalitva approved these changes

2023-05-21 19:56 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        BookingState bookingState;
```java
        try {
            return BookingState.valueOf(state);
        } catch (IllegalArgumentException e) {
            throw new ValidationException("Unknown state: " + state);
        }
```

2023-05-21 19:56 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    public boolean equals(Object o) {
Так может тогда лучше ломбок пусть генерит?)

2023-05-21 19:56 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/repository/BookingSpecifications.java
> +}
Отлично, что разобрался с этой темой предлагаю упросить:
1. Переместить билдеры в BookingState`

```java
public enum BookingState {
    ALL((r, q, cb) -> cb.isTrue(cb.literal(true))),
    CURRENT((r, q, cb) -> cb.between(
            cb.literal(LocalDateTime.now()), r.<LocalDateTime>get("start"), r.<LocalDateTime>get("end"))),
    PAST((r, q, cb) -> cb.lessThan(r.<LocalDateTime>get("end"), LocalDateTime.now())),
    FUTURE((r, q, cb) -> cb.greaterThan(r.<LocalDateTime>get("start"), LocalDateTime.now())),
    WAITING((r, q, cb) -> cb.equal(r.<BookingStatus>get("status"), BookingStatus.WAITING)),
    REJECTED((r, q, cb) -> cb.equal(r.<BookingStatus>get("status"), BookingStatus.REJECTED));

    private final Specification<Booking> specification;

    private BookingState(Specification<Booking> specification) {
        this.specification = specification;
    }

    public Specification<Booking> getSpecification() {
        return specification;
    }
}
```
2.  Предикат по `bookerId` или `ownerId` определять в методе сервиса, затем соединять с предикатом соответствующим state
```java
    public List<Booking> getByBooker(long userId, BookingState state) {
        ...
        Specification<Booking> byBookerId = (r, q, cb) -> cb.equal(r.<Long>get("booker").get("id"), userId);
        return bookingRepository.findAll(Specification.where(byBookerId).and(state.getSpecification()),
                Sort.by(Sort.Direction.DESC, BOOKING_START_DATE_FIELD_NAME));
    }

    public List<Booking> getByOwner(long userId, BookingState state) {
        ...
        Specification<Booking> byOwnerId = (r, q, cb) -> cb.equal(r.<Long>get("item").get("owner").get("id"), userId);
        return bookingRepository.findAll(Specification.where(byOwnerId).and(state.getSpecification()),
                Sort.by(Sort.Direction.DESC, BOOKING_START_DATE_FIELD_NAME));
    }
```

Это также позволит избавиться от свича

2023-05-23 18:56 UTC, merged